### ISSUE TITLE
didDetermineState doesn't work with Secure UUID beacons

### ISSUE THREAD

**Issue by benjaminhallock** [Estimote/iOS-SDK#163] opened 2014-11-20 18:22 UTC
So I've tried to set this up, nothing is working.

1. Put appID and token in AppDelegate.

2. Enabled "Secured" in init method for Beacon Region.

3. Secure my Estimote, then start ranging.

What works is when you manual startRanging, then I get my secure Estimote.

What doesn't is when I notifyOnEntry or Display. didDeterminateState doesn't get called as usual. Secure UUID is what is stopping this.

**Comment by heypiotr** [comment] 2015-02-11 20:56
We're aware of a bug in the `didDetermineState` method that prevents it from working correctly with Secure UUID beacons. That's the root cause of the issue here. Stay tuned for the fix.

**Comment by heypiotr** [comment] 2015-04-08 09:43
Fixed in 3.0.

**Closed by heypiotr** 2015-04-08 09:43 UTC
